src/Entity/Tache.php
<?php

namespace App\Entity;

use App\Repository\TacheRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TacheRepository::class)]
class Tache
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $titre = null;

    #[ORM\Column(type: 'datetime')]
    #[Assert\NotNull()]
    private ?\DateTimeInterface $date_echeance = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull()]
    private ?string $priorite = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull()]
    private ?string $statut = null;

    #[ORM\Column(length: 255)]
    #[Assert\NotNull()]
    private ?string $description = null;

    #[ORM\ManyToOne(inversedBy: 'taches')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    // Getters and setters for each property...
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDateEcheance(): ?\DateTimeInterface
    {
        return $this->date_echeance;
    }

    public function setDateEcheance(\DateTimeInterface $date_echeance): static
    {
        $this->date_echeance = $date_echeance;

        return $this;
    }

    public function getPriorite(): ?string
    {
        return $this->priorite;
    }

    public function setPriorite(string $priorite): static
    {
        $this->priorite = $priorite;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): static
    {
        $this->statut = $statut;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/TacheType.php
<?php

namespace App\Form;

use App\Entity\Tache;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Validator\Constraints\Choice;
use Symfony\Component\Validator\Constraints\Date;
use Symfony\Component\Form\Extension\Core\Type\SubmitType; // Ajoutez cette ligne 
use Symfony\Component\Validator\Constraints\Callback;
use Symfony\Component\Validator\Context\ExecutionContextInterface;



class TacheType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre', TextType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'minlength' => 2,
                    'maxlength' => 50
                ],
                'label' => 'Titre',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new Length(['min' => 2, 'max' => 50]),
                    new NotBlank()
                ]
            ])
            ->add('date_echeance', DateType::class, [
                'attr' => [
                    'class' => 'form-control'
                ],
                'widget' => 'single_text',
                'label' => 'Date d\'échéance',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
            ])
            
            ->add('priorite', ChoiceType::class, [
                'attr' => [
                    'class' => 'form-select'
                ],
                'label' => 'Priorité',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'choices' => [
                    'Basse' => 'Basse',
                    'Moyenne' => 'Moyenne',
                    'Haute' => 'Haute'
                ],
                'constraints' => [
                    new Choice(['choices' => ['Basse', 'Moyenne', 'Haute']])
                ]
            ])
            ->add('statut', ChoiceType::class, [
                'attr' => [
                    'class' => 'form-select'
                ],
                'label' => 'Statut',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'choices' => [
                    'En cours' => 'En cours',
                    'Terminée' => 'Terminée',
                    'À faire' => 'À faire'
                ],
                'constraints' => [
                    new Choice(['choices' => ['En cours', 'Terminée', 'À faire']])
                ]
            ])
            ->add('description', TextareaType::class, [
                'attr' => [
                    'class' => 'form-control',
                    'rows' => 4
                ],
                'label' => 'Description',
                'label_attr' => [
                    'class' => 'form-label mt-4'
                ],
                'constraints' => [
                    new NotBlank()
                ]
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Modifier Tâche',
                'attr' => [
                    'class' => 'btn btn-primary mt-4' // Classe CSS pour le style du bouton
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tache::class,
        ]);
    }
   
}

src/Controller/TacheController.php
<?php

namespace App\Controller;
use App\Repository\TacheRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Knp\Component\Pager\PaginatorInterface;
use App\Entity\Tache;
use App\Form\TacheType;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;
use Symfony\Component\VarDumper\VarDumper;


class TacheController extends AbstractController
{
    /**
     * Undocumented function
     *
     * @param TacheRepository $repository
     * @param PaginatorInterface $paginator
     * @param Request $request
     * @return Response
     */
    #[Route('/tache', name: 'app_tache', methods: ['GET'])]
    public function index(TacheRepository $repository, PaginatorInterface $paginator, Request $request): Response
    {
        $taches = $repository->findBy([], ['date_echeance' => 'ASC']);;

        $statut = $request->query->get('statut');
        $sort = $request->query->get('sort');
        $page = $request->query->getInt('page', 1);

        // Récupérer toutes les tâches de l'utilisateur
        $toutesTaches = $repository->findBy(['user' => $this->getUser()]);

        // Récupération des tâches depuis le repository avec tri et filtre
        $queryBuilder = $repository->createQueryBuilder('t')
            ->where('t.user = :user')
            ->setParameter('user', $this->getUser());

        if ($statut !== null) {
            $queryBuilder->andWhere('t.statut = :statut')
                ->setParameter('statut', $statut);
        }

    

        // Pagination
        $tache = $paginator->paginate(
            $queryBuilder->getQuery(),
            $page,
            4 // Nombre d'éléments par page
        );

    // Comptez le nombre de tâches terminées, en attente et en cours
    $tachesTerminees = array_filter($toutesTaches, function ($tache) {
        return $tache->getStatut() === 'Terminée';
    });

    $tachesEnAttente = array_filter($toutesTaches, function ($tache) {
        return $tache->getStatut() === 'À faire';
    });

    $tachesEnCours = array_filter($toutesTaches, function ($tache) {
        return $tache->getStatut() === 'En cours';
    });

    return $this->render('pages/tache/index.html.twig', [
        'taches' => $tache,
        'totalTachesTerminees' => count($tachesTerminees),
        'totalTachesEnAttente' => count($tachesEnAttente),
        'totalTachesEnCours' => count($tachesEnCours),
    ]);
    
}

    
    #[Route('/{id}', name: 'tache.show', methods: ['GET'])]
    public function show(int $id, TacheRepository $tacheRepository): Response
    {
        $tache = $tacheRepository->find($id);
    
        if (!$tache) {
            throw $this->createNotFoundException('Tache introuvable.');
        }
    
        return $this->render('pages/tache/show.html.twig', [
            'tache' => $tache,
        ]);
    }
    
    

    /**
     * Undocumented function
     *
     * @param Request $request
     * @param EntityManagerInterface $manager
     * @return Response
     */
    #[Route('/tache/nouvelle', name: 'tache.index', methods: ['GET', 'POST'])]

    public function new(
        Request $request,
        EntityManagerInterface $manager
    ) : Response
    {
        // Vérification de l'autorisation manuellement
        if (!$this->isGranted('ROLE_USER')) {
            throw new AccessDeniedException('Accès refusé.');
        }
        $tache = new tache();
        $form = $this->createForm(TacheType::class, $tache);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            $tache = $form->getData();
            $tache->setUser($this->getUser());
            $manager->persist($tache);
            $manager->flush();

            $this->addFlash(
                'success',
                'Votre tache a été créé avec succès !'
            );

            return $this->redirectToRoute('app_tache');
        }

        return $this->render('pages/tache/new.html.twig', [
            'form' => $form->createView()
        ]);
    }

    #[Route('/tache/edition/{id}', name: 'tache.edit', methods: ['GET', 'POST'])]
    public function edit(TacheRepository $repository, int $id, Request $request, EntityManagerInterface $manager): Response
    {
        $tache = $repository->findOneBy(['id' => $id]);

        // Vérification de l'autorisation manuellement
        if (!$this->isGranted('ROLE_USER') || $this->getUser() !== $tache->getUser()) {
            throw new AccessDeniedException('Vous n\'êtes pas autorisé à modifier cette tâche.');
        }

        $form = $this->createForm(TacheType::class, $tache);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $manager->flush();

            $this->addFlash('success', 'Votre tache a été modifiée avec succès !');

            return $this->redirectToRoute('app_tache');
        }

        return $this->render('pages/tache/edit.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/tache/suppression/{id}', 'tache.delete', methods: ['GET'])]
public function delete(TacheRepository $repository, EntityManagerInterface $manager, int $id) : Response 
{
    $tache = $repository->findOneBy(["id" => $id]);
    $manager->remove($tache);
    $manager->flush();

    $this->addFlash(
        'success',
        'Votre tache a été supprimé avec succès !'
    );

    return $this->redirectToRoute('app_tache');
}

    
}

templates/pages/tache/edit.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">

    <h1 class="mt-4">Modification d'une tâche</h1>
    
 {{ form_start(form) }}
    <div class="form-error">
        {{ form_errors(form) }}
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.titre) }}
        </div>
        <div class="col" id="some-custom-id">
            {{ form_row(form.date_echeance) }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.priorite) }}
        </div>
        <div class="col">
            {{ form_row(form.statut) }}
        </div>
    </div>

    {{ form_row(form.description) }}

    {{ form_row(form.submit) }}

<div class="d-flex align-items-end mt-3">
                    <a class="btn btn-outline-secondary animate__animated animate__fadeInLeft" href="{{ path('app_tache') }}">Retour à la liste</a>
                </div>
{{ form_end(form) }}

</div>
{% endblock %}

templates/pages/tache/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Taches{% endblock %}

{% block body %}
    <div class="container mt-3">
    
        <h2>Mes Taches</h2>

        <a href="{{ path('tache.index')}}" class="btn btn-primary mb-3">Créer une tâche</a>


    {% if not taches.items is same as ([]) %}


        <div class="row mb-4">

            <div class="col-sm-3 animate__animated animate__slideInDown">
    <div class="card text-white bg-success mb-3">
        <div class="card-body">
            <h5 class="card-title">Tâches Terminées</h5>
            <p class="card-text">{{ totalTachesTerminees }}</p>
        </div>
    </div>
</div>

            <div class="col-sm-3 animate__animated animate__slideInDown">
                <div class="card text-white bg-warning mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Tâches en Cours</h5>
                        <p class="card-text">{{ totalTachesEnCours }}</p>
                    </div>
                </div>
            </div>

            <div class="col-sm-3 animate__animated animate__slideInDown">
                <div class="card text-white bg-secondary mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Tâches à faire</h5>
                        <p class="card-text">{{ totalTachesEnAttente }}</p>
                    </div>
                </div>
            </div>
            <div class="col-sm-3 animate__animated animate__slideInDown">
                <div class="card text-white bg-info mb-3">
                    <div class="card-body">
                        <h5 class="card-title">Total de Tâches</h5>
                        <p class="card-text">{{ taches.getTotalItemCount }}</p>
                    </div>
                </div>
            </div>
        </div>

            
   <div class="d-flex justify-content-between mb-4 mb-2 animate__animated animate__slideInDown">
    <div class="btn-group" role="group">
        <!-- Menu déroulant de tri -->
     <div class="dropdown">
    <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Trier par
    </button>
    <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
        <a class="dropdown-item" href="{{ path('app_tache', {'sort': 'date_echeance'}) }}">Date</a>
        <a class="dropdown-item" href="{{ path('app_tache', {'sort': 'priorite'}) }}">Priorité</a>
    </div>
</div>


</div>

    </div>

    <div class="btn-group" role="group">
        <!-- Menu déroulant de filtrage -->
        <div class="dropdown">
            <button id="btnGroupDrop2" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Filtrer par statut
            </button>
            <div class="dropdown-menu" aria-labelledby="btnGroupDrop2">
                <a class="dropdown-item" href="{{ path('app_tache', {'sort': app.request.query.get('sort'), 'statut': 'a faire'}) }}">A faire</a>
                <a class="dropdown-item" href="{{ path('app_tache', {'sort': app.request.query.get('sort'), 'statut': 'en cours'}) }}">En cours</a>
                <a class="dropdown-item" href="{{ path('app_tache', {'sort': app.request.query.get('sort'), 'statut': 'terminee'}) }}">Terminée</a>
                <a class="dropdown-item" href="{{ path('app_tache') }}">Toutes les tâches</a>
            </div>
        </div>
    </div>
</div>



            {# read and display just one flash message type #}
        {% for message in app.flashes('success') %}
            <div class="alert alert-success mt-3">
                {{ message }}
            </div>
        {% endfor %}


        <table class="table table-hover my-1">
            <thead>
                <tr>
                    <th scope="col">Numero</th>
                    <th scope="col">Titre</th>
                    <th scope="col">Description</th>
                    <th scope="col">Date d'echéance</th>
                    <th scope="col">Priorité</th>
                    <th scope="col">Status</th>
                    <th scope="col">Edition</th>
                    <th scope="col">Suppression</th>
                </tr>
            </thead>
            <tbody>
                {% for tache in taches %}
                <tr class="table-primarlight">
                    <th scope="row">{{ tache.id }}</th>
                    <td>{{ tache.titre }}</td>
                    <td>{{ tache.description }}</td>
                    <td>{{ tache.dateEcheance|date('Y-m-d') }}</td>
                    <td>{% if tache.priorite == 'Haute' %}
                                    <span class="badge bg-danger">Haute</span>
                                {% elseif tache.priorite == 'Moyenne' %}
                                    <span class="badge bg-warning">Moyenne</span>
                                {% elseif tache.priorite == 'Basse' %}
                                    <span class="badge bg-info">Basse</span>
                                {% endif %}</td>
                    <td>{% if tache.statut == 'Terminée' %}
                                    <span class="badge bg-success">Terminée</span>
                                {% elseif tache.statut == 'En cours' %}
                                    <span class="badge bg-primary">En cours</span>
                                {% elseif tache.statut == 'À faire' %}
                                    <span class="badge bg-secondary">À faire</span>
                                {% endif %}</td>

                       <td>
                   <a href="{{ path('tache.show', {'id': tache.id}) }}" class="btn btn-info">Voir</a>

                    </td>           
                    <td>
                    <a href="{{ path('tache.edit',{ id: tache.id }) }}" class="btn btn-secondary">Modifier</a>
                    </td>
                    <td>
                    
                    <a href="{{ path('tache.delete', { id: tache.id }) }}" class="delete-link btn btn-danger" data-confirm="Êtes-vous sûr de vouloir supprimer cette tâche ?">Supprimer</a>

                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="navigation d-flex justify-content-center mt-3">
    {{ knp_pagination_render(taches) }}
        <script>
            const deleteLinks = document.querySelectorAll('.delete-link');
            
            deleteLinks.forEach(link => {
                link.addEventListener('click', function(event) {
                    event.preventDefault();
                    const confirmationMessage = link.getAttribute('data-confirm');
                    
                    if (confirm(confirmationMessage)) {
                        window.location.href = link.getAttribute('href');
                    }
                });
            });
        </script>
<script>
    $(document).ready(function () {
        // Initialisation des composants Bootstrap
        $('.dropdown-toggle').dropdown();
    });
</script>

</div>
{% else %}
<h4>Il n'a pas de taches</h4>
{% endif %}
    </div>
{% endblock %}

        

templates/pages/tache/new.html.twig
{% extends "base.html.twig" %}

{% block body %}
<div class="container">

    <h1 class="mt-4">Création d'une tâche</h1>
    
 {{ form_start(form) }}
    <div class="form-error">
        {{ form_errors(form) }}
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.titre) }}
        </div>
        <div class="col" id="some-custom-id">
            {{ form_row(form.date_echeance) }}
        </div>
    </div>

    <div class="row">
        <div class="col">
            {{ form_row(form.priorite) }}
        </div>
        <div class="col">
            {{ form_row(form.statut) }}
        </div>
    </div>

    {{ form_row(form.description) }}

    {{ form_row(form.submit) }}

{{ form_end(form) }}

</div>
{% endblock %}

templates/pages/tache/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Taches
{% endblock %}

{% block body %}
<div class="container mt-5 animate__animated animate__fadeIn">
    <h1 class="my-4">Taches</h1>

    <div class="card border-primary mb-3 animate__animated animate__fadeIn">
        <div class="card-body">
            <table class="table table-hover table-striped table-borderless">
                <tbody>
                    <tr class="animate__animated animate__fadeIn">
                        <th scope="row">Titre</th>
                        <td>{{ tache.titre }}</td>
                    </tr>
                    <tr class="animate__animated animate__fadeIn">
                        <th scope="row">Description</th>
                        <td>{{ tache.description }}</td>
                    </tr>
                    <tr class="animate__animated animate__fadeIn">
                        <th scope="row">Date</th>
                        <td>{{ tache.dateEcheance|date('d-m-Y') }}</td>
                    </tr>
                    <tr class="animate__animated animate__fadeIn">
                        <th scope="row">Priorite</th>
                        <td>
                            {% if tache.Priorite == 'Haute' %}
                                <span class="badge bg-danger animate__animated animate__bounceIn">Haute</span>
                            {% elseif tache.Priorite == 'Moyenne' %}
                                <span class="badge bg-warning animate__animated animate__bounceIn">Moyenne</span>
                            {% elseif tache.Priorite == 'Basse' %}
                                <span class="badge bg-info animate__animated animate__bounceIn">Basse</span>
                            {% endif %}
                        </td>
                    </tr>
                    <tr class="animate__animated animate__fadeIn">
                        <th scope="row">Statut</th>
                        <td>
                            {% if tache.statut == 'Terminée' %}
                                <span class="badge bg-success animate__animated animate__bounceIn">Terminée</span>
                            {% elseif tache.statut == 'En cours' %}
                                <span class="badge bg-primary animate__animated animate__bounceIn">En cours</span>
                            {% elseif tache.statut == 'À faire' %}
                                <span class="badge bg-secondary animate__animated animate__bounceIn">À faire</span>
                            {% endif %}
                        </td>
                    </tr>
                </tbody>
            </table>

             <div class="d-flex justify-content-between animate__animated animate__fadeIn">
                <div class="d-flex align-items-end mb-3">
                    <a class="btn btn-outline-secondary animate__animated animate__fadeInLeft" href="{{ path('app_tache') }}">Retour à la liste</a>
                </div>

               <div class="d-flex flex-column align-items-end">
    <a href="{{ path('tache.edit',{ id: tache.id }) }}" class="btn btn-info">Modifier</a>
    <div class="mt-2"> 
        <a href="{{ path('tache.delete', { id: tache.id }) }}" class="delete-link btn btn-danger" data-confirm="Êtes-vous sûr de vouloir supprimer cette tâche ?">Supprimer</a>
    </div>
</div>

            </div> 
        </div>
    </div>
</div>
<script>
            const deleteLinks = document.querySelectorAll('.delete-link');
            
            deleteLinks.forEach(link => {
                link.addEventListener('click', function(event) {
                    event.preventDefault();
                    const confirmationMessage = link.getAttribute('data-confirm');
                    
                    if (confirm(confirmationMessage)) {
                        window.location.href = link.getAttribute('href');
                    }
                });
            });
        </script>
{% endblock %}